git:
  depth: 1
language: ruby

rvm: 2.3.0

sudo: false

cache: bundler

gemfile: Gemfile

bundler_args: --without development --deployment

before_script:
  - bundle exec rake -v db:create db:test:prepare

script: bundle exec rake -v test

env:
  - DB=postgres
