git:
  depth: 1
language: ruby

rvm: 2.3.0

sudo: false

cache: bundler

gemfile: Gemfile

bundler_args: --without development --deployment

before_script:
  - bundle exec rake -v db:create db:test:prepare

script: bundle exec rake -v test

env:
  - DB=postgres

# Gitter integration
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/02574f759a5344e72aec
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
